<?php
require_once("application/includes/classes/Configuration.inc.php");
include_once('public/html/html.inc.php');
startHtml('Contact Us');
siteMenu("Contact Us");
?>
<style>
.green {
	color: #000;
}
.nav-tabs > li > a:hover, .nav-pills > li > a, .nav-pills > li > a:hover {
	color: #000;
}

        <!--
        /* Font Definitions */
        @font-face
        {font-family:Wingdings;
            panose-1:5 0 0 0 0 0 0 0 0 0;}
        @font-face
        {font-family:"Cambria Math";
            panose-1:2 4 5 3 5 4 6 3 2 4;}
        @font-face
        {font-family:Calibri;
            panose-1:2 15 5 2 2 2 4 3 2 4;}
        @font-face
        {font-family:"Calibri Light";
            panose-1:2 15 3 2 2 2 4 3 2 4;}
        @font-face
        {font-family:"Segoe UI";
            panose-1:2 11 5 2 4 2 4 2 2 3;}
        /* Style Definitions */
        p.MsoNormal, li.MsoNormal, div.MsoNormal
        {margin-top:0in;
            margin-right:0in;
            margin-bottom:8.0pt;
            margin-left:0in;
            line-height:107%;
            font-size:11.0pt;
            font-family:"Calibri",sans-serif;}
        h1
        {mso-style-link:"Heading 1 Char";
            margin-top:12.0pt;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:0in;
            margin-bottom:.0001pt;
            line-height:107%;
            page-break-after:avoid;
            font-size:16.0pt;
            font-family:"Calibri Light",sans-serif;
            color:#2E74B5;
            font-weight:normal;}
        h3
        {mso-style-link:"Heading 3 Char";
            margin-top:2.0pt;
            margin-right:0in;
            margin-bottom:0in;
            margin-left:0in;
            margin-bottom:.0001pt;
            line-height:107%;
            page-break-after:avoid;
            font-size:12.0pt;
            font-family:"Calibri Light",sans-serif;
            color:#1F4D78;
            font-weight:normal;}
        -->
    </style>

<div class=" page-content-wrapper">
    <div class="page-content landing-content"><br />
        <div class="col-md-12 ">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">What's New</div>
                </div>
                <div class="portlet-body" style="min-height:500px;">
                    <div class=WordSection1>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.35pt;
text-indent:0in;line-height:107%'><span style='font-size:
24.0pt;mso-bidi-font-size:11.0pt;line-height:107%;color:#2D74B5'>Contraceptive
LMIS R2.4 Release - Highlights </span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:11.9pt;
margin-left:.1pt;text-indent:0in;line-height:107%'><span style='font-size:16.0pt;
mso-bidi-font-size:11.0pt;line-height:107%;color:#2D74B5'>cLMIS R3 release
provides the updates/enhancement for users of public sector working in supply
chain at various levels. </span><span style='font-size:16.0pt;mso-bidi-font-size:
11.0pt;line-height:107%;color:#2E74B5'>All the requirements were generated by
the stakeholders, tested and approved during the UAT and requires no additional
resources for implementation.</span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:11.9pt;
margin-left:.1pt;text-indent:0in;line-height:107%'><span style='font-size:16.0pt;
mso-bidi-font-size:11.0pt;line-height:107%;color:#2D74B5'>Main highlights of
enhanced features are as follows: </span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.1pt;margin-bottom:.0001pt;text-indent:0in;line-height:107%'><b style='mso-bidi-font-weight:normal'>District
Stock Sufficiency Dashboard</b> has been developed and is incorporate for use
by different stakeholders at district level. The dashboard aims to review
Family Planning (FP) commodity sufficiency at district and its Service Delivery
Points (SDPs) level. The report is parameterized so that it may be run against
data up to an indicated month &amp; highlights the stock issued from the
central warehouse but not yet received at district level along with stock
requested to central warehouse. The dashboard is an SDP level drill down for a
deeper insight into commodity wise stock level. 
</span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.1pt;margin-bottom:.0001pt;text-indent:0in;line-height:107%'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='margin-right:4.85pt;text-align:justify;text-justify:
inter-ideograph'><b style='mso-bidi-font-weight:normal'>Stock outs analysis
Reports </b>is developed for the analysis of stock at sub-district level by
provincial decision makers &amp; presents total number of &amp; reported
Service Delivery Points (SDPs), 
</span>stockedout, under, over as well as satisfactory stock level in any
province. </p>

<p class=MsoNormal style='margin-right:4.85pt;text-align:justify;text-justify:
inter-ideograph'><b style='mso-bidi-font-weight:normal'>M&amp;E Dashboard </b>captures
consumption trends and month of stock and aids in yearly consumption and stock
availability analysis at a district or health facility level. </p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:7.95pt;
margin-left:-.15pt;text-indent:-.5pt;line-height:107%'><b style='mso-bidi-font-weight:
normal'>Ease of Use &amp; navigation </b>– Reduction in Existing 12 Reports to
3 reports i.e. Summary Reports, Yearly Reports, performance Reports.<span
style='mso-spacerun:yes'>   </span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:4.85pt;margin-bottom:
5.5pt;margin-left:-.2pt'><b style='mso-bidi-font-weight:normal'>Combined Requisition
Cycle </b>In the current devolved scenario, provincial level stakeholders like
IRMNCH in Punjab or PWD in Sindh are procuring contraceptives for different
programs and stocks are stored in Central warehouse as their combined stock.
Different programs obtain contraceptives from these stakeholders e.g. LHW, MNCH
and DoH (static health facilities). This module enables generation of<span
style='mso-spacerun:yes'>  </span>decentralized provincial distribution plan
and requisition cycle which is flagged to central warehouse electronically for issuance.
The issuance from central warehouse is notified to provincial departments &amp;
when these stocks are received at the district level central warehouse and
provincial departments are notified. </p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.9pt;
margin-left:0in;text-indent:0in;line-height:107%'><b style='mso-bidi-font-weight:
normal'>Actionable alerts </b></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.9pt;
margin-left:0in;text-indent:0in;line-height:107%'><b style='mso-bidi-font-weight:
normal'>   </span>a.<span
style='mso-spacerun:yes'>  </span>E</b>xpiry and Shipment Alerts – CWS Level</p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.9pt;
margin-left:0in;text-indent:0in;line-height:107%'><span
style='mso-spacerun:yes'>   </span>b. Stockout alerts - Provincial and District
Level</p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.9pt;
margin-left:0in;text-indent:0in;line-height:107%'><b>System Usage Stats:</b>
System usage stats, webserver logs, system availablity and uptime, pages click
paths, list of active logged in users are implemented to provide a holistic
360* view of the system usage and performance at every level</p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.9pt;
margin-left:0in;text-indent:0in;line-height:107%'><b>User Feed back &amp;
Profile Form</b> is provided to update the user’s profile in cLMIS. The logged
in user can submit his/her feedback through this form as well. </p>

<p class=MsoNormal style='margin-top:0in;margin-right:4.85pt;margin-bottom:
7.7pt;margin-left:-.2pt'><b>Sustainability of LMIS: </b>Routine admin tasks are
pushed to selected end users to curtail reliance on the MIS team as a
sustainability measure. These users will be able to manage the warehouse,
locations, facilities as well as users. The related interfaces are live on the
system.  </span></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.9pt;
margin-left:0in;text-indent:0in;line-height:107%'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='margin-top:0in;margin-right:0in;margin-bottom:4.9pt;
margin-left:0in;text-indent:0in;line-height:107%'><o:p>&nbsp;</o:p></p>

</div>
                </div>
            </div>
        </div>
        
        <!-- BEGIN  PATNERS -->
        <div class="row">
            <div class="col-lg-12">
                <div class="tab-content stake-holder">stakeholders</div>
                <ul class="nav nav-tabs stake-holder-list">
                    <li> <img src="<?php echo PUBLIC_URL; ?>assets/frontend/layout/img/contraceptive-partners/govt-of-pak-logo.png" alt=""/></li>
                    <li> <img src="<?php echo PUBLIC_URL; ?>assets/frontend/layout/img/contraceptive-partners/us-aid-logo.png" alt=""/></li>
                </ul>
            </div>
        </div>
        <!-- END PATNERS --> 
    </div>
</div>
</div>
</div>
<?php
endHtml();
?>